### ISSUE TITLE
Table zoauth_consumer

### ISSUE THREAD

**Issue by larshp** [ivanfemia/abap2gapps#3]
Hi,
Looks like `zoauth_consumer` is missing in the repo?

https://github.com/ivanfemia/abap2gapps/blob/6bf5778ee39c2f531af9fde159cd95684395a457/src/z_gaabap_setup_2_register_user.prog.abap#L121

**Comment by ivanfemia** [comment]
This project depends on abap2oauth repo

**Comment by larshp** [comment]
ahh, okay, closing
